### ISSUE TITLE
Setup testing as Cookbook 1?

### ISSUE THREAD

**Issue by richelbilderbeek** [mywtfmp3/boost_graph_cookbook_2#2]
Cookbook 1 uses a folder `boost_graph_cookbook_1` to store its files, qmake for creating makefiles and Travis CI to run all tests.

Would it help if I'd set this up, so you would have a beginning? After that, you can ruthlessly alter it :+1:

**Comment by JohnCoconut** [comment]
Yes. That's what I want to. Please help.

**Comment by JohnCoconut** [comment]
Please do whatever you want with this repo at the moment, since it's empty.

**Comment by richelbilderbeek** [comment]
Great. After fixing (mostly renaming) Cookbook 1, I will do so, which will be in some hours.

**Comment by richelbilderbeek** [comment]
I've set it up. Make yourself at home! 

You know who to assign for more help on this :+1:
