### ISSUE TITLE
Activate Travis CI

### ISSUE THREAD

**Issue by richelbilderbeek** [mywtfmp3/boost_graph_cookbook_2#4]
Hi @mywtfmp3 , I cannot activate Travis CI, could you do so [here](https://travis-ci.org/mywtfmp3/boost_graph_cookbook_2)? 

I do assume you enjoy continuous integration, as this helped our collaboration to flourish as well.

**Comment by JohnCoconut** [comment]
Done

**Comment by richelbilderbeek** [comment]
:+1:
