### ISSUE TITLE
Acticate Codecov

### ISSUE THREAD

**Issue by richelbilderbeek** [mywtfmp3/boost_graph_cookbook_2#5]
Hi @mywtfmp3 , I do not have the rights to do so myself: could you activate Codecov [here](https://codecov.io/github/mywtfmp3/boost_graph_cookbook_2)? One can login with a GitHub account and it's free.

Thanks!

**Comment by JohnCoconut** [comment]
Done.

**Comment by richelbilderbeek** [comment]
:+1:
