### ISSUE TITLE
Target audience of this book

### ISSUE THREAD

**Issue by JohnCoconut** [mywtfmp3/boost_graph_cookbook_2#6]
What's our assumption of audience's knowledge on graph algorithm and C++?

1. On C++, book 1 assumes readers are familiar with basics, templates, lambda, STL containers and algorithms. 

2. On graph algorithm, shall we assume they're familiar with graph algorithms but not familiar with BGL algorithms?

**Comment by richelbilderbeek** [comment]
Agreed.

The most disputable point IMHO would be assuming familiarity with graph algorithms. From experience, I know I can find these online. What is absent online is how to use these on simple examples.

Keep up the good work :+1:

**Comment by JohnCoconut** [comment]
I will write a small chapter on breath first search and ask you for a review when it's done.

Let's see what balance is required to get the content flowing.

> The most disputable point IMHO would be assuming familiarity with graph algorithms

That's what I am thinking too. Some of the algorithms are quite complicated. But I need to stop worrying about it and get the work done.
