### ISSUE TITLE
How to draw grid graph aligned in horizontal direction?

### ISSUE THREAD

**Issue by JohnCoconut** [mywtfmp3/boost_graph_cookbook_2#7]
https://www.boost.org/doc/libs/1_67_0/libs/graph/doc/grid_graph.html

Grid graph is a graph that looks like this (from BGL documentation),

![grid_graph_unwrapped](https://user-images.githubusercontent.com/3619244/40098701-7284aec6-590f-11e8-96fd-c772af5e6e9b.png)

A two dimensional (3 x 3) grid graph is created with,
```cpp
boost::grid_graph<2> g({3, 3});
```

I want to use grid graph to represent maze. So I draw something similar with the `neato` program,
```bash
neato -Tpng  grid.dot -O
```

![grid dot](https://user-images.githubusercontent.com/3619244/40098752-ad680a92-590f-11e8-88d2-5617d8e1bf0a.png)

I don't care about the color. The problem is the vertex index and alignment. I hope they are aligned like,

[6, 7, 8]
[3, 4, 5]
[0, 1, 2]

@richelbilderbeek Do you have any idea how to do it? I am wondering if there's a way to do it with `boost::write_graphviz` by generating proper dot file.

**Comment by richelbilderbeek** [comment]
I guess it can be done, using a custom vertex writer that takes column and row into account. I do have never do so in practice however. 

If you find an easy way, please let me know.

If you need it for you algorithms -which I read you do- and prefer to put graph grids already in Book 1, I will do so. OTOH, you may prefer having a 'Create advanced grids' in Book 2. 

If you want me to try this Saturday, let me know.

**Comment by JohnCoconut** [comment]
https://stackoverflow.com/questions/5343899/how-to-force-node-position-x-and-y-in-graphviz shows "pos" attribute can be used to set the position of vertex. I will try to do it sometime tomorrow.

I think grid graph and filtered graph are appropriate for Book1. The concept is simple but can be useful in certain cases.

**Comment by JohnCoconut** [comment]
I am able to align the graph properly by using a custom propery writer to write "pos" attribute of vertex in dot file. It's better than before, although the overall rectangular shape are not perfect (the edge looks bended). But I can live with it.

```cpp
#include <iostream>

#include <boost/graph/grid_graph.hpp>
#include <boost/graph/graphviz.hpp>
#include <boost/array.hpp>

struct PosWriter
{
  template <typename Vertex>
  void operator()(std::ostream& out, const Vertex& v)
  {
    out << "[pos=\"" << v[0] << "," << v[1] << "\"]";
  }
};

int main()
{
  using Graph = boost::grid_graph<2>;
  boost::array<std::size_t, 2> lengths = {8, 4};
  Graph g(lengths);
  std::ofstream file("grid.dot");
  boost::write_graphviz(file, g, PosWriter());

  return 0;
}
```

![grid dot](https://user-images.githubusercontent.com/3619244/40186048-b9a627e0-5a26-11e8-8c50-584228254114.png)

As post above, the png format graph is generated by,

```bash
neato -Tpng  -O grid.dot
```
