### ISSUE TITLE
What's wrong with this simple bfs search algorithm?

### ISSUE THREAD

**Issue by JohnCoconut** [mywtfmp3/boost_graph_cookbook_2#8]
@richelbilderbeek I am kind of stuck with my simple breath first search program.

I have a complete binary tree. I want to print the distance of each node to its root. For example,  `d[0, 0] = 0, d[0, 1] = 1, d[0, 2] = 1, d[0, 3] = 2, d[0, 7] = 3`. 

![graph dot](https://user-images.githubusercontent.com/3619244/40625359-8317ba06-62e4-11e8-959d-5561fc8ad3b3.png)

The dot file is here.
```
digraph G {
0;
1;
2;
3;
4;
5;
6;
7;
8;
9;
10;
11;
12;
13;
14;
0->1 ;
0->2 ;
1->3 ;
1->4 ;
2->5 ;
2->6 ;
3->7 ;
3->8 ;
4->9 ;
4->10 ;
5->11 ;
5->12 ;
6->13 ;
6->14 ;
}
```

The program is pretty straightforward, `make_bfs_visitor` take a `distance_recorder` to record the distance between tree edges.

```C++
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/breadth_first_search.hpp>
#include <boost/graph/graphviz.hpp>

int main()
{
    using DiGraph = boost::adjacency_list<>;
    DiGraph g;
    std::ifstream dot_file("graph.dot");
    boost::dynamic_properties dp{ boost::ignore_other_properties };
    boost::read_graphviz(dot_file, g, dp);

    auto vd0 = *boost::vertices(g).first;

    using vertices_size_type = boost::graph_traits<DiGraph>::vertices_size_type;

    std::vector<vertices_size_type> distances(boost::num_vertices(g));
    auto dist_pmap = boost::make_iterator_property_map(
        distances.begin(), get(boost::vertex_index, g));

    auto vis = boost::make_bfs_visitor(
        boost::record_distances(dist_pmap, boost::on_tree_edge()));

    boost::breadth_first_search(g, vd0, visitor(vis));

    for (auto d : distances)
        std::cout << d << ' ';
    std::cout << '\n';

    for (auto d : boost::make_iterator_range(boost::vertices(g)))
      std::cout << d << ' ';
    std::cout << '\n';
    return 0;
}
```

The output is not what I expected.
```bash
0 1 3 3 3 3 3 1 2 2 2 2 3 3 3 
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 
```

Do you have any clue? If not, I may ask in stackoverflow.

**Comment by richelbilderbeek** [comment]
I suggest to ask SO, as I have never worked with visitors: you use a lot of functions unknown to me.

**Comment by JohnCoconut** [comment]
sehe@stackoverflow answered my question.

https://stackoverflow.com/questions/50583130/how-does-distance-recorder-work-in-boost-graph-library

The problem is with `read_graphviz` rather than `breath_first_visit`. When reading the graph from the dot file, If `dynamic_properteis` is set to `boost::ignore_other_properties`, the graph constructed from dot file is **only isomorphic** to the graph shown above. There's no guarantee that the vertex number in dot file is the same as the graph generated by `read_graphviz`. This catches me off guard. See images below.-

Original graph.
![graph dot](https://user-images.githubusercontent.com/3619244/40699132-3d57b90e-6405-11e8-9476-19432981bae4.png)

Generated by `read_graphviz`.
![out dot](https://user-images.githubusercontent.com/3619244/40699148-55f6e566-6405-11e8-840e-15e8b3144a49.png)



Do you think we should mention this in Algorithm 57 (*Loading a directed graph from a .dot file*) ? Or shall we add a new algorithm just after 57?

**Comment by JohnCoconut** [comment]
I will be on holiday for two weeks. I won't be active on github in the meantime. Maybe I will be more productive in writing when I am offline. Good luck.

**Comment by richelbilderbeek** [comment]
Enjoy your holiday :+1:
