### ISSUE TITLE
visualize graph algorithm

### ISSUE THREAD

**Issue by JohnCoconut** [mywtfmp3/boost_graph_cookbook_2#9]
There is a website for visualizing algorithms, for example on depth first search, https://visualgo.net/en/dfsbfs.

However, it has a very strict license.

>If you are a data structure and algorithm student/instructor, you are allowed to use this website directly for your classes. If you take screen shots (videos) from this website, you can use the screen shots (videos) elsewhere as long as you cite the URL of this website (http://visualgo.net) and/or list of publications below as reference. However, you are NOT allowed to download VisuAlgo (client-side) files and host it on your own website as it is plagiarism. As of now, we do NOT allow other people to fork this project and create variants of VisuAlgo. Using the offline copy of (client-side) VisuAlgo for your personal usage is fine.

It doesn't allow customizing behavior on each step of algorithm. 

I want to have an program that let me do such things,

* traverse the graph step by step 
* run custom function on the step
* show the result at the end

This will let me visualize every algorithm in boost graph library.

@richelbilderbeek Do you know any easy way to create animations(like the one on visualgo website) using whatever tools that's convenient?

**Comment by richelbilderbeek** [comment]
Getting it that fancy will be hard.

For animations, I usually stitch together PNGs, e.g. like [as described here](https://askubuntu.com/a/269905)

**Comment by JohnCoconut** [comment]
Seems great, I will see how to plot a gif showing breath first search.
